[custom]
custom_proxy_group=✔️ 节点选择`select`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,5
custom_proxy_group=✳️ 专用下载`load-balance`(专用X)`http://www.gstatic.com/generate_204`300
custom_proxy_group=❇️ 电报下载`url-test`(TS)`http://www.gstatic.com/generate_204`300,,50

; 1. BT 专属分流
custom_rule=PROCESS-NAME,qbittorrent-nox,✳️ 专用下载
custom_rule=DOMAIN-KEYWORD,tracker,✳️ 专用下载
custom_rule=DOMAIN-KEYWORD,torrent,✳️ 专用下载

; 2. TG 专属分流 (调用内核自带全量数据库，秒杀一切漏网IP)
custom_rule=GEOSITE,telegram,❇️ 电报下载
custom_rule=GEOIP,telegram,❇️ 电报下载

; 3. 局域网与国内环境直连 (调用内核底层数据库)
custom_rule=GEOIP,lan,DIRECT,no-resolve
custom_rule=GEOSITE,cn,DIRECT
custom_rule=GEOIP,cn,DIRECT

; 4. 终极兜底：其他所有流量走节点
custom_rule=MATCH,✔️ 节点选择

enable_rule_generator=false
overwrite_original_rules=true
