[custom]
; 1. 极简基础策略组 (仅保留手动和自动)
custom_proxy_group=✔️ 节点选择`select`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,5

; 2. 注入专属下载节点组 (名称与 Emoji 严格对应)
custom_proxy_group=✳️ 专用下载`load-balance`(专用X)`http://www.gstatic.com/generate_204`300
custom_proxy_group=❇️ 电报下载`url-test`(TS)`http://www.gstatic.com/generate_204`300,,50

; 3. 专属分流规则 (最高优先级拦截)
custom_rule=PROCESS-NAME,qbittorrent-nox,✳️ 专用下载
custom_rule=DOMAIN-KEYWORD,tracker,✳️ 专用下载
custom_rule=DOMAIN-KEYWORD,torrent,✳️ 专用下载
custom_rule=DOMAIN-SUFFIX,telegram.org,❇️ 电报下载
custom_rule=DOMAIN-SUFFIX,telegram.dog,❇️ 电报下载
custom_rule=DOMAIN-SUFFIX,telegra.ph,❇️ 电报下载
custom_rule=DOMAIN-SUFFIX,t.me,❇️ 电报下载

; 4. 网络分流列表
; 局域网直连 (防止内网面板死锁)
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
; 国内域名与 IP 直连 (加速云盘映射与国内网站访问，节省代理流量)
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list

; 兜底：剩下的所有外网杂项流量，统一走常规代理
ruleset=✔️ 节点选择,[]FINAL

enable_rule_generator=true
overwrite_original_rules=true
